@startuml erd

  entity "organizations" {
    + id [PK] <color:gray>integer</color>
    --
    name <color:gray>string</color>
    created_at <color:gray>datetime</color>
    updated_at <color:gray>datetime</color>
  }

  entity "users" {
    + id [PK] <color:gray>integer</color>
    --
    # organization_id [FK] <color:gray>bigint</color>
    name <color:gray>string</color>
    email <color:gray>string</color>
    password <color:gray>string</color>
    is_admin <color:gray>boolean</color>
    created_at <color:gray>datetime</color>
    updated_at <color:gray>datetime</color>
  }

  entity "projects" {
    + id [PK] <color:gray>integer</color>
    --
    # organization_id [FK] <color:gray>bigint</color>
    name <color:gray>string</color>
    description <color:gray>text</color>
    is_done <color:gray>boolean</color>
    is_archived <color:gray>boolean</color>
    created_at <color:gray>datetime</color>
    updated_at <color:gray>datetime</color>
  }

  entity "tasks" {
    + id [PK] <color:gray>integer</color>
    --
    # project_id [FK] <color:gray>bigint</color>
    name <color:gray>string</color>
    start_at <color:gray>date</color>
    end_at <color:gray>date</color>
    description <color:gray>text</color>
    is_done <color:gray>boolean</color>
    row_order <color:gray>integer</color>
    created_at <color:gray>datetime</color>
    updated_at <color:gray>datetime</color>
  }

  entity "project_members" {
    + id [PK] <color:gray>integer</color>
    --
    # project_id [FK] <color:gray>bigint</color>
    # user_id [FK] <color:gray>bigint</color>
    created_at <color:gray>datetime</color>
    updated_at <color:gray>datetime</color>
  }

  entity "task_staffs" {
    + id [PK] <color:gray>integer</color>
    --
    # task_id [FK] <color:gray>bigint</color>
    # user_id [FK] <color:gray>bigint</color>
    created_at <color:gray>datetime</color>
    updated_at <color:gray>datetime</color>
  }

@enduml
